### ISSUE TITLE
Popis

### ISSUE THREAD

**Issue by ChroustJan** [ust-modules/USTSIPM01#1]
PCB má vzniknout spojením dvou modulů:
https://github.com/mlab-modules/STEPUPDC01
https://github.com/mlab-modules/SIPM02

U měniče je potřeba vyměnit cívka. 400uH (proud cca 0,9mA).  odporovej delic 3M9 / 160k
![277683201_509654740782872_7492841513016585274_n](https://user-images.githubusercontent.com/9783606/163167179-d6c1c76d-f8d7-4ca9-86e0-371733eded12.jpg)

**Comment by kaklik** [comment]
Tohle issue se mi nezdá kompletní. Respektive se asi zapomíná na [dřívější poznatky z geodosů](https://github.com/mlab-modules/PCRD06/issues).  Zejména asi jde o [snazší výrobu při spojování modulů](https://github.com/mlab-modules/PCRD06/issues/3).

**Comment by kaklik** [comment]
Tenhle nekompletní popis přestal být relevantní.
